#! /bin/bash

set -e

MY_IP=$(curl -s https://checkip.amazonaws.com)

aws ec2 authorize-security-group-ingress \
    --group-name trainium-workshop-sg \
    --protocol tcp \
    --port 22 \
    --cidr $MY_IP/32 > /dev/null 2>&1 || true

export INSTANCE_IP=$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=TrainiumWorkshop" "Name=instance-state-name,Values=running" \
    --query "Reservations[0].Instances[0].PublicIpAddress" \
    --output text)

exec nc "$INSTANCE_IP" 22